In [7]:
import numpy as np

def maxnet(v,eps):
    unique, index = np.unique(v,return_index=True)
    for i in range(len(v)):
        if i not in index:
            v[i]=0
    W = np.full((len(v),len(v)),-eps);np.fill_diagonal(W, 1)
    while np.count_nonzero(v) != 1:
        v = np.matmul(W,v).clip(min=0)
    return v.argmax()

def hamming(E, V):
    W = (E/2).T.copy()
    b = len(V)/2
    output = []
    for v in V:
        i = maxnet(np.matmul(v, W)+b,0.3)
        output.append((v, E[i]))
    return output

In [8]:
e1 = [1, -1, 1, -1, 1, -1]
e2 = [-1, 1, -1, 1, -1, -1]
e3 = [1, 1, 1, -1, -1, -1]
E = np.array([e1, e2, e3])

V1 = [-1, 1, -1, 1, -1, 1]
V2 = [1, 1, 1, -1, -1, 1]
V3 = [1, -1, -1, -1, -1, 1]

V = np.array([V1, V2, V3,])
hamming(E=E, V=V)

[(array([-1,  1, -1,  1, -1,  1]), array([-1,  1, -1,  1, -1, -1])),
 (array([ 1,  1,  1, -1, -1,  1]), array([ 1,  1,  1, -1, -1, -1])),
 (array([ 1, -1, -1, -1, -1,  1]), array([ 1, -1,  1, -1,  1, -1]))]

In [9]:
V1 = [1, 1, 1, 1, 1, 1]
V2 = [-1, 1, -1, -1, 1, 1]
V3 = [-1, -1, 1, 1, 1, 1]
V4 = [-1, -1, 1, 1, -1, 1]
V5 = [-1, 1, 1, -1, -1, -1]

V = np.array([V1, V2, V3, V4, V5])
hamming(E=E, V=V)

[(array([1, 1, 1, 1, 1, 1]), array([ 1, -1,  1, -1,  1, -1])),
 (array([-1,  1, -1, -1,  1,  1]), array([-1,  1, -1,  1, -1, -1])),
 (array([-1, -1,  1,  1,  1,  1]), array([ 1, -1,  1, -1,  1, -1])),
 (array([-1, -1,  1,  1, -1,  1]), array([-1,  1, -1,  1, -1, -1])),
 (array([-1,  1,  1, -1, -1, -1]), array([ 1,  1,  1, -1, -1, -1]))]